config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  
  devise_for :users
  resources :books do
    member do
      patch 'publish_book'
    end
    collection do
      get 'sort_books'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one :user
  
  mount_uploader :book_cover, BookCoverUploader
  
  validates :book_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  layout 'application_layout'
  
  before_action :authenticate_user!, except: [:show]
  before_action :find_book, only: [:edit,:update,:show,:destroy,:publish_book]
  
  def index
    @books = current_user.books.order(:publish_status)
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(books_params.merge(:user_id => current_user.id))
    if @book.save
      flash[:success] = "Successfully Created Book"
      redirect_to books_path
    else
      flash[:error] = @book.errors.full_messages.uniq.join(', ')
      render :new
    end
  end
  
  def edit
  end
  
  def update
    book = @book.update_attributes(books_params)
    if book
      flash[:success] = "Successfully Updated Book"
      redirect_to books_path
    else
      flash[:error] = @book.errors.full_messages.uniq.join(', ')
      render :edit
    end
    
  end
  
  def show
  end
  
  def destroy
    delete_book = @book.delete
    flash[:success] = "Successfully Deleted Book" if delete_book
    flash[:error] = @book.errors.full_messages.uniq.join(', ') if !delete_book
    redirect_to books_path
  end
  
  def publish_book
    @book.update_attribute(:publish_status, params[:status])
  end
  
  def sort_books
    @books = current_user.books.order("#{params[:sort_obj]} #{params[:sort_order]}")
    params[:sort_order] = (params[:sort_order] == "ASC") ? "DESC" : "ASC"
    @arrow_class =  (params[:sort_order] == "ASC") ? ["fa fa-angle-down","fa fa-angle-up"] : ["fa fa-angle-up","fa fa-angle-down"]
  end
  
  private
  
  def books_params
    params.require(:book).permit(:book_name,:book_cover,:author,:isbn,:price,:category,:publish_status)
  end
  
  def find_book
    @book = Book.find_by_id(params[:id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  layout 'application_layout'
  
  def index
    @books = Book.where(:publish_status => true)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_action_buttons.html.erb
<%=link_to edit_book_path(book.id) do%>
	<span class="fa fa-edit edit_icon"></span>
<%end%>
<%=link_to book_path(book.id), remote: true do%>
	<span class="fa fa-search view_icon"></span>
<%end%>
<%=link_to book_path(book.id), method: :delete do%>
	<span class="fa fa-trash delete_icon"></span>
<%end%>

app/views/books/_book_details.html.erb
<div class="col-12 show_header">
	<span class="header_style">Header</span>
	<span class="close_window">X</span>
</div>
<div class="col-12">
	<div class="col-lg-4 left_sec" style="float: left;">
  		<span class="book_cover">
  			<%= (!@book.blank? && !@book.book_cover.blank?) ? image_tag(@book.book_cover_url) : image_tag("Silhouette.png")%>
  		</span>
	</div>
	<div class="col-lg-8 right_sec">
		<span class="details_sec">
			<span class="name">Book Name : </span>
			<span class="description"><%= @book.book_name %></span>
		</span>
		<span class="details_sec">
			<span class="name">Author : </span>
			<span class="description"><%= @book.author %></span>
		</span>
		<span class="details_sec">
			<span class="name">ISBN : </span>
			<span class="description"><%= @book.isbn %></span>
		</span>
		<span class="details_sec">
			<span class="name">Price : </span>
			<span class="description"><%= @book.price %></span>
		</span>
		<span class="details_sec">
			<span class="name">Category : </span>
			<span class="description"><%= @book.category %></span>
		</span>
	</div>
	
</div>

app/views/books/_books_list.html.erb
<div class="book_view_header">
	<span class="header">Actions</span>
	<span class="header sort_list book_name" data-sort-obj="book_name" data-sort-order="ASC" title="Click to sort">
		<span>Book Name</span>
		<span class="sort_arrow"></span>
	</span>
	<span class="header sort_list author" data-sort-obj="author" data-sort-order="ASC" title="Click to sort">
		<span>Author</span>
		<span class="sort_arrow"></span>
	</span>
	<span class="header sort_list isbn" data-sort-obj="isbn" data-sort-order="ASC" title="Click to sort">
		<span>ISBN</span>
		<span class="sort_arrow"></span>
	</span>
	<span class="header sort_list price" data-sort-obj="price" data-sort-order="ASC" title="Click to sort">
		<span>Price</span>
		<span class="sort_arrow"></span>
	</span>
	<span class="header sort_list category" data-sort-obj="category" data-sort-order="ASC" title="Click to sort">
		<span>Category</span>
		<span class="sort_arrow"></span>
	</span>
	<span class="header sort_list publish_status" data-sort-obj="publish_status" data-sort-order="DESC" title="Click to sort">
		<span>Publish / Withhold</span>
		<span class="sort_arrow"></span>
	</span>
</div>
<%@books.each_with_index do |book,index|%>
	<div class="book_view_contents">
		<span class="content"><%=render 'action_buttons', book: book%></span>
		<span class="content" style="width: 24%"><%=book.book_name %></span>
		<span class="content"><%=book.author %></span>
		<span class="content"><%=book.isbn%></span>
		<span class="content">Rs. <%=book.price%></span>
		<span class="content"><%=book.category%></span>
		<span class="content publish_book book_<%=book.id%>" title="Click to publish the book">
			<%=render 'publish_status', book: book%>
		</span>
	</div>
<%end%>

app/views/books/_form.html.erb
<div class="form-wrapper user_profile">
	<div class="photo_section">
	  	<div class="photo_display_sec">
	  		<span id="target" class="image_div">
	  			<%= (!@book.blank? && !@book.book_cover.blank?) ? image_tag(@book.book_cover_url(:thumb)) : image_tag("Silhouette.png")%>
	  		</span>
	  	</div>
	  	<div id="photo_size_check" class="selectPhoto">                                    
	   		<%= form.file_field :book_cover, :id=>"pictureInput", :class => "file_field_new file_field_class", :style =>"display:none;"  %>
	      	<div class= "dropzone_class" id="dropzone" style="cursor:pointer;" onclick="attachment_input(this)" ondragover="allowDrop(event)" ondrop="drop(event)">
	        	<span class="fa fa-upload upload_image" aria-hidden="true" id ="add_attachment_placeholder" ></span>
	        	<input class="order_number detail_view_user upload_box" type="text" readonly="true" id="add_attachment_placeholder" placeholder="Upload Book Cover">
	      	</div>
	  	</div>
  	</div>
	<div class="page-form">
		<div class="row"><%= form.text_field :book_name, class: "form-control", placeholder: "Book Name" %></div>
		<div class="row"><%= form.text_field :author, class: "form-control", placeholder: "Author" %></div>
		<div class="row"><%= form.text_field :isbn, class: "form-control", placeholder: "ISBN" %></div>
		<div class="row"><%= form.number_field :price, class: "form-control", placeholder: "Price", step: :any %></div>
		<div class="row"><%= form.text_field :category, class: "form-control", placeholder: "Category" %></div>
		<div class="row">
			<%= form.submit "Submit", :class=>"btn btn-warning" %>
			<%=link_to books_path do %><span class="btn btn-warning" style="margin-left: 10px;">Cancel</span><%end%>
		</div>
	</div>
</div>

app/views/books/_publish_status.html.erb
<% if book.publish_status %>
	<%=link_to publish_book_book_path(id: book.id, status: false), method: :patch, remote: true do%>
		<span class="status_false">Withhold</span>
	<%end%>
<%else%>
	<%=link_to publish_book_book_path(id: book.id, status: true), method: :patch, remote: true do%>
		<span class="status_true">Publish</span>
	<%end%>
<%end%>

app/views/books/edit.html.erb
<div class="breadcrumbs" style="background:#6f5b92;color:#FFF;">
	<span class="fa fa-home"></span> / Books / <span class="active">Edit</span>
</div>
<div>
	<%= form_with model: @book do |form|%>
		<%= render "form", form: form%>
	<%end%>
</div>

app/views/books/index.html.erb
<% if !@books.blank? %>
	<div id="books_list" style="width:100%;float: left;">
		<%= render "books_list"%>
	</div>
<%else%>
	<div class="noRecords"><span class="fa fa-info-circle"></span> No Books Found</div>
<%end%>

app/views/books/new.html.erb
<div class="breadcrumbs" style="background:#6f5b92;color:#FFF;">
	<span class="fa fa-home"></span> / Books / <span class="active">New</span>
</div>
<div>
	<%= form_with model: @book do |form|%>
		<%= render "form", form: form%>
	<%end%>
</div>

app/views/books/publish_book.js.erb
$('.book_<%=@book.id%>').html("<%=escape_javascript(render("publish_status", book: @book))%>");

app/views/books/show.js.erb
$("#model_window_main_view").html("");
$("#model_window_main_view").html("<%=escape_javascript(render("book_details"))%>");
$("#model_window_main_view").show();
$(".light_box_wrapper").show();

app/views/books/sort_books.js.erb
$("#books_list").html("<%=escape_javascript(render("books_list"))%>");
$(".sort_arrow").removeClass("<%=@arrow_class[0]%>")
$(".<%=params[:sort_obj]%>").find('.sort_arrow').addClass("<%=@arrow_class[1]%>")
$(".<%=params[:sort_obj]%>").data('sort-order',"<%=params[:sort_order]%>")

app/views/home/index.html.erb
<%if !@books.blank?%>
	<div class="album-grid">
		<% @books.each do |book|%>
			<div class="album-item">
				<%=link_to book_path(book.id), remote: true do %>
					<div class="album-content">
						<div class="image"><%=image_tag book.book_cover_url(:thumb) %></div>
						<div class="name"><%=book.book_name%></div>	
					</div>
				<%end%>
			</div>
		<%end%>
	</div>
<%else%>
	<div class="noRecords"><span class="fa fa-info-circle"></span> No Books Found</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookRegistry</title>
     <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

</html>

app/views/layouts/application_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
  	<header>
  		<div class="logo">
  			<span>
  				<%=link_to root_url do%>
  					<div>BookRegistry</div>
  				<%end%>
  			</span>
  		</div>
		<div class="navigation">
			<%if current_user%>
				<div class="nav">
					<%= link_to "Add Books", new_book_path%>
				</div>
				<div class="nav">
					<%= link_to "Publish Books", books_path%>
				</div>
			<%end%>
		</div>
  		<div class="profile">
  			<%if current_user%>
	  			<div class="action">
	  				<%= current_user.email %>
	  			</div>
	  			<div class="action">
	  				<%= link_to "Logout", destroy_user_session_path, method: :delete%>
	  			</div>
	  		<%else%>
	  			<div class="action">
	  				<%= link_to "Log in", new_user_session_path %>
	  			</div>
	  			<div class="action">
	  				<%= link_to "Sign up", new_user_registration_path %>
	  			</div>
  			<%end%>
  		</div>
  		
  	</header>
  	
  	<% if flash[:error]%>
	  	<div class="notification error">
	  		<div class="icon"><span class="fa fa-info-circle"></span></div>
	  		<div class="message"><%=flash[:error]%></div>
	  		<div class="close_notice"  onclick="$('.error').hide();"><span class="fa fa-times"></span></div>
	  	</div>
  	<%end%>
  	
  	<% if flash[:success]%>
	  	<div class="notification success">
	  		<div class="icon"><span class="fa fa-check-circle"></span></div>
	  		<div class="message"><%=flash[:success]%></div>
	  		<div class="close_notice" onclick="$('.success').hide();"><span class="fa fa-times"></span></div>
	  	</div>
  	<%end%>
  	
  	<div class="page-outer-contents">
		<div class="page-contents">
	    	<%= yield %>
	    </div>
	</div>
	
	<div id="model_window_main_view"></div>
	<div class="light_box_wrapper"></div>
	
  </body>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

</html>